#  ______  __
#  ___  / / /______________________  __
#  __  /_/ /_  __ \_  __ \  _ \_  / / /
#  _  __  / / /_/ /  / / /  __/  /_/ /
#  /_/ /_/  \____//_/ /_/\___/_\__, /
#                             /____/
# Resource Page: https://modrinth.com/project/xQ3pgVap
# Wiki: https://github.com/leonesoj/honey/wiki

database:
  # Options: SQLite or MySQL(required on a Velocity network)
  provider: "SQLite"
  config:
    host: ""
    database: "honey"
    port: 2025
    username: ""
    password: ""

cache:
  # Options: In-Memory or Redis(required on a Velocity network)
  # If you're running a single server instance, strongly consider switching to Redis if you experience
  # high memory usage. As in-memory cache stores all data in-memory.
  provider: "in-memory"
  # Upstash offers a very capable free Redis database with affordable paid options, if you need to scale
  redis_config:
    host: ""
    port: 2025
    password: ""
    ssl: true

server:
  # This identifier must be unique across your entire network.
  identifier: "hive1"
  # Server links are useful for listing information regarding your server like announcements, forums
  # status, support, etc.
  links:
    honey: # This key can be anything
      display_name: "<white>Powered by</white> <i><gradient:#FFA142:#F6C26B>Honey</gradient></i>"
      url: "https://modrinth.com/project/xQ3pgVap" # URL must be formatted properly
  listing:
    show_player_list: false # Shows a small list of online players, excluding staff mode players
    hide_player_count: false # If this option is disabled, player count will be displayed as ???
    motd:
      entry_one:
        icon: "honey_icon"
        lines:
          - "                     <gold>🗡</gold> <gray>Minecraft Server</gray> <gold>⛏</gold>"
          - "                                           <gray>Powered by</gray> <gold><i>Honey</i></gold>"
      entry_two:
        icon: "bee_icon"
        lines:
          - "<gold>Bzzzzzzzz...</gold>"

chat:
  # Default channel is the chat channel for which all users will be automatically added as a participant
  default_channel: "general"
  # Placeholders:
  # - <display_name> : The player's display name(maybe changed by other plugins)
  # - <username> : The player's username(static and always reflects their true name)
  # - <prefix> : The player's prefix denoted by their primary group
  # - <suffix> : The player's suffix denoted by their primary group
  # Permissions:
  # - Slow Talk Bypass : honey.chat.<channel_identifier_here>.bypass.slow
  # - Mute Talk Bypass : honey.chat.<channel_identifier_here>.bypass.mute
  channels:
    general:
      format: "<gray><display_name>:</gray> <white><message></white>"
    staff:
      format: "<gray>[<dark_red><b>!</b></dark_red>]</gray> <gold><display_name>:</gold> <white><message></white>"
  private_messaging:
    format:
      to_user: "<gray>(<i>You</i> » <recipient>):</gray> <white><message></white>"
      from_user: "<gray>(<sender> » <i>You</i>):</gray> <white><message></white>"
  spy:
    format:
      command: <gray><<light_purple>#</light_purple>> <player>:</gray> <command>
      private_message: <gray><<aqua>✉</aqua>> (<player> » <recipient>):</gray> <message>
  variables:
    enabled: true
    require_permission: false
  slow_duration: 5
  cooldown_duration: 3
  history_size: 3

reports:
  # Amount of time a user must wait before submitting another successful report in seconds.
  # Default: 900s = 15m
  report_cooldown: 900

# At first startup, a secret key will automatically be generated, DO NOT change this value
# under any circumstances as various features will break.
# This secret key is used for hashing purposes to keep your player's sensitive information hidden
# in the case of a database breach.
secret: ""