name: Honey
version: ${version}
main: io.github.leonesoj.honey.Honey
description: A streamlined backend for modern Minecraft servers.
authors: [ Termxs ]
api-version: '1.21.10'
loader: io.github.leonesoj.honey.HoneyLoader
bootstrapper: io.github.leonesoj.honey.HoneyBootstrap
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false