name: Honey
version: ${version}
main: io.github.leonesoj.honey.Honey
description: A streamlined backend for modern Minecraft servers.
authors: [ Termxs ]
api-version: '1.21.8'
loader: io.github.leonesoj.honey.HoneyLoader
bootstrapper: io.github.leonesoj.honey.HoneyBootstrap
dependencies:
  bootstrap:
    Apollo-Bukkit:
      load: BEFORE
      required: false
      join-classpath: true
  server:
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    ProtocolLib:
      load: BEFORE
      required: false
    Apollo-Bukkit:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false